---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "hivent-events-api"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
- name: "events"
paths:
  /events:
    get:
      tags:
      - "events"
      operationId: "findEvents"
      parameters:
      - name: "groupId"
        in: "query"
        required: false
        type: "integer"
        format: "int64"
      - name: "typeGroup"
        in: "query"
        required: false
        type: "string"
      - name: "beginDate"
        in: "query"
        required: false
        type: "string"
        format: "date-time"
      - name: "endDate"
        in: "query"
        required: false
        type: "string"
        format: "date-time"
      - name: "idUser"
        in: "query"
        required: false
        type: "integer"
        format: "int64"
      - name: "interestedId"
        in: "query"
        required: false
        type: "integer"
        format: "int64"
      - name: "administratorId"
        in: "query"
        required: false
        type: "integer"
        format: "int64"
      - name: "participantId"
        in: "query"
        required: false
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Lecture réussie."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/EventBE"
        404:
          description: "Ressource introuvable."
          schema:
            $ref: "#/definitions/ReponseErreur"
      x-swagger-router-controller: "Events"
    post:
      tags:
      - "events"
      operationId: "createEvent"
      parameters:
      - in: "body"
        name: "event"
        required: true
        schema:
          $ref: "#/definitions/EventBE"
      responses:
        201:
          description: "Création réussie."
          schema:
            $ref: "#/definitions/EventBE"
          headers:
            Location:
              type: "string"
              description: "URI de la ressource créée"
        400:
          description: "Erreur lors de la création."
          schema:
            $ref: "#/definitions/ReponseErreur"
        404:
          description: "Ressource introuvable."
          schema:
            $ref: "#/definitions/ReponseErreur"
      x-swagger-router-controller: "Events"
  /events/{id}:
    get:
      tags:
      - "events"
      operationId: "readEvent"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Lecture réussie."
          schema:
            $ref: "#/definitions/EventBE"
        404:
          description: "Ressource introuvable."
          schema:
            $ref: "#/definitions/ReponseErreur"
      x-swagger-router-controller: "Events"
    put:
      tags:
      - "events"
      operationId: "updateEvent"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "event"
        required: true
        schema:
          $ref: "#/definitions/EventBE"
      responses:
        200:
          description: "Mise à jour réussie."
          schema:
            $ref: "#/definitions/EventBE"
        400:
          description: "Erreur lors de la mise à jour."
          schema:
            $ref: "#/definitions/ReponseErreur"
        404:
          description: "Ressource introuvable."
          schema:
            $ref: "#/definitions/ReponseErreur"
      x-swagger-router-controller: "Events"
    delete:
      tags:
      - "events"
      operationId: "deleteEvent"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        204:
          description: "Suppression réussie."
        400:
          description: "Erreur lors de la suppression."
          schema:
            $ref: "#/definitions/ReponseErreur"
        404:
          description: "Ressource introuvable."
          schema:
            $ref: "#/definitions/ReponseErreur"
      x-swagger-router-controller: "Events"
definitions:
  EventBE:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        description: "Identifiant.Lecture seule.\n"
      name:
        type: "string"
      description:
        type: "string"
      startDate:
        type: "string"
        format: "date-time"
      endDate:
        type: "string"
        format: "date-time"
      idCalendarEvent:
        type: "string"
      resources:
        type: "array"
        items:
          $ref: "#/definitions/ResourceXBE"
      group:
        $ref: "#/definitions/GroupXBE"
      interested:
        type: "array"
        items:
          $ref: "#/definitions/UserXBE"
      participants:
        type: "array"
        items:
          $ref: "#/definitions/UserXBE"
      administrators:
        type: "array"
        items:
          $ref: "#/definitions/UserXBE"
  ResourceXBE:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        description: "Identifiant.Lecture seule.\n"
      mailResource:
        type: "string"
  GroupXBE:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        description: "Identifiant.Lecture seule.\n"
      typeWorkGroup:
        $ref: "#/definitions/TypeWorkGroupEnum"
  UserXBE:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        description: "Identifiant.Lecture seule.\n"
      firstname:
        type: "string"
      lastname:
        type: "string"
      mail:
        type: "string"
  TypeWorkGroupEnum:
    description: "TypeWorkGroupEnum"
    enum:
    - "WORKSHOP"
    - "PROJECT"
  StateEnum:
    description: "StateEnum"
    enum:
    - "OPENED"
    - "FULLED"
    - "CANCELED"
  ReponseErreur:
    type: "object"
    properties:
      erreurs:
        type: "array"
        items:
          $ref: "#/definitions/ReponseErreur_erreurs"
  ReponseErreur_erreurs:
    properties:
      champErreur:
        type: "string"
      codeErreur:
        type: "string"
      libelleErreur:
        type: "string"
